
import type { Metadata } from 'next';
import './globals.css';


export const metadata: Metadata = {
  title: 'figma-test-project',
  description: 'Generated by Next.js Modular Project Generator',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>

          <header style={{ padding: '1rem', backgroundColor: '#f0f0f0', borderBottom: '1px solid #ddd', marginBottom: '1rem' }}>
            <nav>
              <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', gap: '15px' }}>
                <li><a href="/">Home</a></li>
                <li><a href="/blog">Simple Blog Blog</a></li>
                <li><a href="/blog/[slug]">Simple Blog [slug]</a></li>
                <li><a href="/contact">Contact Form Contact</a></li>
                <li><a href="/faq">FAQ Module Faq</a></li>
              </ul>
            </nav>
          </header>

        {children}
      </body>
    </html>
  );
}
